### ISSUE TITLE
CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by Gamer4Life2020** [n00mkrad/cupscale#104]
Having issues trying to run. I have tried two different computers, python 3.8/3.9 and Win10/11.
All have the same issue so not sure if it's a cupscale, python, or driver issue.

[CMD] /C cd /D "C:\Users\User\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\bin\esrgan-pytorch" & python upscale.py --input "C:\Users\User\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\preview" --output "C:\Users\User\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\preview-out"   --device_id 1 --fp16  --alpha_mode 0   "C:\Users\User\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\models\ESRGAN\4x_RealSR_DF2K_JPEG.pth"
[Python] Model: 4x_RealSR_DF2K_JPEG
[Python] Traceback (most recent call last):
[Python] Upscaling...
[Python]   File "C:\Users\User\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\bin\esrgan-pytorch\upscale.py", line 368, in <module>
[Python]     load_model(model_path)
[Python]   File "C:\Users\User\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\bin\esrgan-pytorch\upscale.py", line 230, in load_model
[Python]     model = model.to(device)
[Python]   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 899, in to
[Python]     return self._apply(convert)
[Python]   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 570, in _apply
[Python]     module._apply(fn)
[Python]   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 570, in _apply
[Python]     module._apply(fn)
[Python] 1 preview.png.png
[Python]   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 593, in _apply
[Python] Image loaded
[Python]     param_applied = fn(param)
[Python] Reloading model - model_path: C:\Users\User\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\models\ESRGAN\4x_RealSR_DF2K_JPEG.pth - last_model: None
[Python]   File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 897, in convert
[Python] Setting last_model to C:\Users\User\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\models\ESRGAN\4x_RealSR_DF2K_JPEG.pth
[Python]     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
[Python] RuntimeError: CUDA error: invalid device ordinal
[Python] CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
[Python] For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[ESRGAN] Upscaling Error: Index was outside the bounds of the array.
   at Cupscale.Main.Upscale.<Run>d__8.MoveNext()

Cards are a RTX 3070 and a Quadro P620

**Comment by Gamer4Life2020** [comment]
So, it works fine was my fault. Windows shows CPU GPU as 0 and Nvidia as 1, so was using GPU 1 and not 0.
Changed to 0 to try and all is well.
