### ISSUE TITLE
Error: Can't find upscaled output image! This probably means the AI implementation failed to run correctly.

### ISSUE THREAD

**Issue by godzfire** [n00mkrad/cupscale#115]
When clicking Upscale And Save button I get the following:

Error: Can't find upscaled output image! This probably means the AI implementation failed to run correctly.
Index was outside the bounds of the array.
Stack Trace:
   at Cupscale.Main.Upscale.GetOutputImg()
The error message was copied to the clipboard.

Error during FilenamePostprocess(): 
File name cannot be null.
Parameter name: sourceFileName
Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)
The error message was copied to the clipboard.

---------------------

Running in portable mode. Data folder: C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData
Arg: C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\Cupscale.exe
[IOUtils] Copying directory "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\esrgan-pytorch\utils" to "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\utils" (Move: False - RemoveFromName: )
Failed to initialize NvApi: Unable to load DLL 'nvapi64': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Ignore this if you don't have an Nvidia GPU.
[DepCheck] CMD: /C python -V
[Servers] Ping to nmkd-hz.de: 154 ms
[DepCheck] System Python Check Output: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
[DepCheck] Sys Python Ver: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
[DepCheck] CMD: /C "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\python.exe" -V
[DepCheck] Embed Python Check Output: Python 3.8.5
[DepCheck] Embed Python Ver: Python 3.8.5
Parsing Patrons from CSV...
Found 13 Gold Patrons, 363 Silver Patrons
[Servers] Ping to nmkd-cb.de: 49 ms
[Servers] Closest Server: USA (St. Louis) (49 ms)
[MainUI] Dropped 1 file(s), first = C:\Users\godzfire\Desktop\input.jpg
[ImgProc] Converting C:\Users\godzfire\Desktop\input.jpg to PngRaw, DelSrc: False, Fill: True, Ext: UseNew
[ImgProc] Color depth of input.jpg is 24.
[ImgProc] Written image to C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\loaded-img\temp.png
[ImgProc] Preprocessing C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\img-in\input.jpg - Fill Alpha: True
[ImgProc] Color depth of input.jpg is 24.
[CMD] /C cd /D "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\esrgan-pytorch" & "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\python.exe" upscale.py --input "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\img-in" --output "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\img-out"   --device_id 0 --fp16  --alpha_mode 0   "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\models\ESRGAN\4x_BSRGAN.pth"
[Python] Model: 4x_BSRGAN
[Python] Upscaling...
[Python] 1 input.jpg.png
[Python] Image loaded
[Python] Reloading model - model_path: C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\models\ESRGAN\4x_BSRGAN.pth - last_model: None
[Python] Setting last_model to C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\models\ESRGAN\4x_BSRGAN.pth
[Python] Traceback (most recent call last):
[Python]   File "upscale.py", line 368, in <module>
[Python]     load_model(model_path)
[Python]   File "upscale.py", line 230, in load_model
[Python]     model = model.to(device)
[Python]   File "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\nn\modules\module.py", line 607, in to
[Python]     return self._apply(convert)
[Python]   File "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
[Python]     module._apply(fn)
[Python]   File "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
[Python]     module._apply(fn)
[Python]   File "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\nn\modules\module.py", line 376, in _apply
[Python]     param_applied = fn(param)
[Python]   File "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\nn\modules\module.py", line 605, in convert
[Python]     return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
[Python]   File "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\cuda\__init__.py", line 186, in _lazy_init
[Python]     _check_driver()
[Python]   File "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\cuda\__init__.py", line 65, in _check_driver
[Python]     raise AssertionError("""
[Python] AssertionError: 
[Python] Found no NVIDIA driver on your system. Please check that you
[Python] have an NVIDIA GPU and installed a driver from
[Python] http://www.nvidia.com/Download/index.aspx
Error: Can't find upscaled output image! This probably means the AI implementation failed to run correctly.

Index was outside the bounds of the array.

Stack Trace:
   at Cupscale.Main.Upscale.GetOutputImg()
FilenamePostprocess: Moving  => -4x_BSRGAN
Error during FilenamePostprocess(): 

File name cannot be null.
Parameter name: sourceFileName

Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)
Overwrite is off - keeping suffix.
[IOUtils] Copying directory "C:\Users\godzfire\Desktop\Cupscale 1.39.0f1\CupscaleData\img-out" to "C:\Users\godzfire\Desktop" (Move: False - RemoveFromName: )

<img width="361" alt="image" src="https://user-images.githubusercontent.com/2067820/154909996-00cd5f2b-0c9b-4570-bdc2-8fa049ef2ac6.png">

**Comment by DrPleaseRespect** [comment]
It looks like you used Pytorch for Upscaling even though you don't have an NVIDIA Graphics Card.

Use NCNN if you don't have an NVIDIA Graphics Card.

**Comment by shmup** [comment]
That is exactly what I did wrong, so thanks for clarifying @DrPleaseRespect 

1) `pip install ncnn`
2) change your network to use `ncnn` instead of `pytorch`

![image](https://user-images.githubusercontent.com/118710/187564277-cab14b0d-e4f4-4f1e-9260-57699fbd8ac5.png)

**Comment by DrPleaseRespect** [comment]
You don't actually need to install NCNN using pip.. NCNN is a different executable

**Comment by shmup** [comment]
Ah, just removed it and indeed I did not need this library. Thanks for the quick reply

**Comment by ChristianVaughn** [comment]
Anyone know what to do if you have this issue, but you do have a Nvidia GPU? trying to run this using my 4080 super, and i get the same Error: Can't find upscaled output image! error
