### ISSUE TITLE
Error message when creating finished file

### ISSUE THREAD

**Issue by cudadotsln** [n00mkrad/cupscale#127]
Whenever I try to upscale a .png it always gives me this error:

Error during FilenamePostprocess(): 

File name cannot be null.
Parameter name: sourceFileName

Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)

I am using a laptop, and I don't have NVIDIA, I am using the PyTorch network.

**Comment by YmmitZtrol** [comment]
I too can confirm this problem

Furthermore I get the following assertion error: 
"AssertionError: Torch not compiler with CUDA enabled" 

Running on a Laptop with a Nvidia RTX 3070ti

Edit, by following [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/ ) I've managed to fix the problem

**Comment by CiteClimb** [comment]
This solution might seem unrelated, but this fixed it for me: https://github.com/n00mkrad/cupscale/issues/135
