### ISSUE TITLE
upscales no longer working

### ISSUE THREAD

**Issue by probablewitch** [n00mkrad/cupscale#139]
Cupscale suddenly stopped working for me - I had been using it frequently over the past couple of weeks and haven't made any changes, so I'm not sure what's causing the issue.

Sometimes, I will attempt an upscale and it will say "Done" in <5 seconds without generating any new files. Other times, I get this error:

Error during FilenamePostprocess(): 

File name cannot be null.
Parameter name: sourceFileName

Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)

Error during FilenamePostprocess(): 

File name cannot be null.
Parameter name: sourceFileName

Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)

Cupscale installed at C:\Cupscale 1.39.0f1 and images located at C:\Upscaling, all dependencies are met. I checked and made sure the image doesn't have any weird characters in the file name.

**Comment by BrewHog** [comment]
I am seeing the exact same thing.

**Comment by dreamhacking** [comment]
same thing here :(

**Comment by localcake** [comment]
Same here

**Comment by dreamhacking** [comment]
Mine was simple I didn't have python installed after window reset
