### ISSUE TITLE
Nothing is happening? 

### ISSUE THREAD

**Issue by akmeibabu** [n00mkrad/cupscale#140]
Hello! I've tried to troubleshoot and haven't been able to solve this independently.
I've tried different models, images, image types, etc. (No illegal characters in filenames) 
The check file dependencies is all happy and green too.

When I try to upscale and save I receive this error:

Error during FilenamePostprocess(): 

File name cannot be null.
Parameter name: sourceFileName

Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)

I went to settings to have it open the cmd window so I could try to figure out what was happening, but it doesn't do anything...? It just sits with:

Cupscale 1.39.0f1\CupscaleData\bin\esrgan-pytorch>

Any advice would be appreciated! Thank you!

**Comment by mrstuff** [comment]
i too same same even after a reinstall of:                                          (sorry so long)
Python, CUDA , Miniconda, and pytorch 
 it was working ; and  i deleted some files elsewhere and added a bunch of new models , i can get as much technical info as i know how to get to reproduce,
 would that mean using the debug feature in visual studio?

 i haven't the foggiest idea what im doing but was really enjoying Cupscale ! thank you btw
on drag and drop (the image is there)


 
Failed to load image:

String was not recognized as a valid Boolean.

Stack Trace:
   at System.Boolean.Parse(String value)

Status changed: Loading image...
[ImgUtils] Reading MagickImage from C:\Users\mrstu\Pictures\image9.webp-16.jpg [OK]
Status changed: Ready.
Failed to reload image from source path - Maybe image is from clipboard or has been deleted. String was not recognized as a valid Boolean.
Failed to load image:

String was not recognized as a valid Boolean.

Stack Trace:
   at System.Boolean.Parse(String value)
   at Cupscale.Main.MainForm.<ReloadImage>d__41.MoveNext()




System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at Cupscale.UI.BatchUpscaleUI.<Run>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Cupscale.Main.MainForm.<upscaleBtn_Click>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Cupscale
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Magick.NET.Core
    Assembly Version: 6.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.23.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4579.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Cyotek.Windows.Forms.ImageBox
    Assembly Version: 1.2.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4579.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
HTAlt WinForms
    Assembly Version: 0.1.6.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
HTAlt.Standart
    Assembly Version: 0.1.6.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
NvAPIWrapper
    Assembly Version: 0.8.1.100
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.0.1
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4579.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4579.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4579.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
PaintDotNet.Base
    Assembly Version: 3.36.7079.22820
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
DdsFileTypePlus
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
Cyotek.Windows.Forms.TabList
    Assembly Version: 2.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/mrstu/Downloads/Cupscale.1.39.0f1/Cupscale%201.39.0f1/Cupscale.exe
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
