### ISSUE TITLE
RuntimeError: Model is a zip archive

### ISSUE THREAD

**Issue by starkgate** [n00mkrad/cupscale#31]
I'm getting the error in the title when running foolhardy's Remacri model. 

The model: https://discord.com/channels/547949405949657098/579685650824036387/830149073259986965

Dependencies:
![Cupscale_2021-04-16_16-33-39](https://user-images.githubusercontent.com/12874678/115040681-f7f03480-9ed1-11eb-9b1b-944e8bf8ceb2.png)

The log:
```
[Python] Model: 4x_general foolhardy_Remacri
[Python] Upscaling...
[Python] 1 preview.png.png
[Python] Image loaded
[Python] Reloading model - model_path: C:\TOOLS\ImageEnhancingUtility\esrgan\models\4x_general foolhardy_Remacri.pth - last_model: None
[Python] Traceback (most recent call last):
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 187, in nti
[Python]     n = int(s.strip() or "0", 8)
[Python] ValueError: invalid literal for int() with base 8: '_v2\nq\x03(('
[Python] 
[Python] During handling of the above exception, another exception occurred:
[Python] 
[Python] Traceback (most recent call last):
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 2289, in next
[Python]     tarinfo = self.tarinfo.fromtarfile(self)
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 1095, in fromtarfile
[Python]     obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 1037, in frombuf
[Python]     chksum = nti(buf[148:156])
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 189, in nti
[Python]     raise InvalidHeaderError("invalid header")
[Python] tarfile.InvalidHeaderError: invalid header
[Python] 
[Python] During handling of the above exception, another exception occurred:
[Python] 
[Python] Traceback (most recent call last):
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 556, in _load
[Python]     return legacy_load(f)
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 467, in legacy_load
[Python]     with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 1591, in open
[Python]     return func(name, filemode, fileobj, **kwargs)
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 1621, in taropen
[Python]     return cls(name, mode, fileobj, **kwargs)
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 1484, in __init__
[Python]     self.firstmember = self.next()
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 2301, in next
[Python]     raise ReadError(str(e))
[Python] tarfile.ReadError: invalid header
[Python] 
[Python] During handling of the above exception, another exception occurred:
[Python] 
[Python] Traceback (most recent call last):
[Python]   File "upscale.py", line 368, in <module>
[Python]     load_model(model_path)
[Python]   File "upscale.py", line 148, in load_model
[Python]     state_dict = torch.load(model_path)
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 387, in load
[Python]     return _load(f, map_location, pickle_module, **pickle_load_args)
[Python]   File "C:\Users\w42\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 560, in _load
[Python]     raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
[Python] RuntimeError: C:\TOOLS\ImageEnhancingUtility\esrgan\models\4x_general foolhardy_Remacri.pth is a zip archive (did you mean to use torch.jit.load()?)
```

**Comment by n00mkrad** [comment]
Your Pytorch is too old.

Update it to at least 1.6, otherwise some models won't work.

**Comment by starkgate** [comment]
Thank you, that fixes the problem. I have now another problem that occurs when the network is running:

```
[Python] Upscaling...
[Python] 1 preview.png.png
[Python] Image loaded
[Python] Reloading model - model_path: C:\TOOLS\ImageEnhancingUtility\esrgan\models\4x_foolhardy_Remacri.pth - last_model: None
[Python] Setting last_model to C:\TOOLS\ImageEnhancingUtility\esrgan\models\4x_foolhardy_Remacri.pth
[Python] Upscaling image...
[Python] Traceback (most recent call last):
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\utils\dataops.py", line 31, in auto_split_upscale
[Python]     result = upscale_function(lr_img)
[Python]   File "upscale.py", line 282, in upscale
[Python]     output = process(img1)
[Python]   File "upscale.py", line 126, in process
[Python]     output = model(img_LR).data.squeeze(
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
[Python]     result = self.forward(*input, **kwargs)
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\utils\architecture.py", line 72, in forward
[Python]     x = self.model(x)
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
[Python]     result = self.forward(*input, **kwargs)
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\Lib\site-packages\torch\nn\modules\container.py", line 117, in forward
[Python]     input = module(input)
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
[Python]     result = self.forward(*input, **kwargs)
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\Lib\site-packages\torch\nn\modules\upsampling.py", line 141, in forward
[Python]     return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\Lib\site-packages\torch\nn\functional.py", line 3143, in interpolate
[Python]     return torch._C._nn.upsample_nearest2d(input, output_size, sfl[0], sfl[1])
[Python] RuntimeError: CUDA error: unspecified launch failure
[Python] 
[Python] During handling of the above exception, another exception occurred:
[Python] 
[Python] Traceback (most recent call last):
[Python]   File "upscale.py", line 375, in <module>
[Python]     rlt, depth, _ = ops.auto_split_upscale(img, upscale, last_scale)
[Python]   File "C:\TOOLS\Cupscale1.37.0\CupscaleData\ShippedEsrgan\py\utils\dataops.py", line 43, in auto_split_upscale
[Python]     raise RuntimeError(e)
[Python] RuntimeError: CUDA error: unspecified launch failure
```

**Comment by n00mkrad** [comment]
Disable any overclocks and try again

**Comment by starkgate** [comment]
> Disable any overclocks and try again

I don't have any overclocking going on, it's a pretty basic laptop.

**Comment by aizuon** [comment]
Is it possible for you to upload that model? The link on the model database doesnt work anymore
