### ISSUE TITLE
KeyError: 'model.0.weigh BasicSR ESRGAN

### ISSUE THREAD

**Issue by wolfam0108** [n00mkrad/cupscale#42]
Hey! I tried using the xinnta BasicSR based learning model. But unfortunately I get an error.
Is it possible to work in cupscale using BasicSR ESRGAN models?

[CMD] /C cd /D "E:\Portable\prog\Cupscale\CupscaleData\ShippedEsrgan" & python upscale.py --input "E:\Portable\prog\Cupscale\CupscaleData\img-in" --output "E:\Portable\prog\Cupscale\CupscaleData\img-out"   --device_id 0  --seamless  --alpha_mode 0   "E:\Portable\prog\ImageEnhancingUtility\ImageEnhancingUtility\models\my_models\4xManga_set2_d_60000.pth"
[Python] Model: 4xManga_set2_d_60000
[Python] Traceback (most recent call last):
[Python] Upscaling...
[Python]   File "upscale.py", line 368, in <module>
[Python] 1 009.jpg.png
[Python]     load_model(model_path)
[Python] Image loaded
[Python]   File "upscale.py", line 204, in load_model
[Python] Reloading model - model_path: E:\Portable\prog\ImageEnhancingUtility\ImageEnhancingUtility\models\my_models\4xManga_set2_d_60000.pth - last_model: None
[Python]     in_nc = state_dict['model.0.weight'].shape[1]
[Python] KeyError: 'model.0.weight'

**Comment by RebelFinatic** [comment]
I'm getting this exact same error.
