### ISSUE TITLE
Upscaling video failed after image preprocessing

### ISSUE THREAD

**Issue by AVerteC** [n00mkrad/cupscale#49]
Cupscale crashes interpolation after preprocessing a mkv video?

In the img-in folder the images start out as 0001.png but when the preprocessing finishes each image name becomes like 0001.png.png.png
I'm not sure if this is what causes the error.

I also selected ``` overwrite mode - yes ```  and ``` mp4 ``` in the saving options

Thanks for your help.

Video upscaling logs
```
Detected frame rate of video as 47.95
Extracting frames...
Done - Extracted 4979 frames.
Preprocessing frames...
Done preprocessing.
Upscaling frames...
Cancelled - next to progress bar in bottom left
```

Session Log
```
Status changed: Converting 4977.png
[ImgUtils] Reading MagickImage from E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4977.png [OK]
[ImgProc] Preprocessing E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4977.png - Fill Alpha: False
[ImgProc] Color depth of 4977.png is 24.
[ImgProc] Deleting source file: E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4977.png
Status changed: Converting 4978.png
[ImgUtils] Reading MagickImage from E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4978.png [OK]
[ImgProc] Preprocessing E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4978.png - Fill Alpha: False
[ImgProc] Color depth of 4978.png is 24.
[ImgProc] Deleting source file: E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4978.png
Status changed: Converting 4979.png
[ImgUtils] Reading MagickImage from E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4979.png [OK]
[ImgProc] Preprocessing E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4979.png - Fill Alpha: False
[ImgProc] Color depth of 4979.png is 24.
[ImgProc] Deleting source file: E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in\4979.png
[ImgProc] Done pre-processing images
Disk space check for E: with multiplier 2 - 3398 MB needed, 103490 MB available
Status changed: Loading images...
[IOUtils] Clearing E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-out
currentInDir: E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in, imgInPath: E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-in
Status changed: Pre-Processing...
[Queue] Start()
[IOUtils] Clearing E:\Cupscale1.37.0\Cupscale1.37.0\CupscaleData\img-out-ncnn
Status changed: Starting ESRGAN...
Status changed: Cancelled.
[ESRGAN] Upscaling Error: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Cupscale.Config.GetInt(String key)
   at Cupscale.OS.ESRGAN.<Run>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Cupscale.OS.ESRGAN.<DoUpscale>d__2.MoveNext()
```

**Comment by AVerteC** [comment]
I think this is a model compatibility issue instead? I have no idea which models to put into the model folder
