### ISSUE TITLE
Error during FilenamePostprocess():   Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by MiLO83** [n00mkrad/cupscale#60]
Error during FilenamePostprocess(): 

Cannot create a file when that file already exists.

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)

**Comment by Randalmcdaniel** [comment]
the batch of files you were working on were set to read only
