### ISSUE TITLE
Video with "Chain Two Models" produces 'Illegal characters in path' error

### ISSUE THREAD

**Issue by becky-soda** [n00mkrad/cupscale#7]
Hi everyone. I'm sorry for bothering you all.

When trying to upscale a video with "Chain Two Models", I get an 'Illegal characters in path' error, and the video file is not created.

I've tried running Cupscale from several locations, and storing the video file in several locations (including "C:\Video\"). I've tried renaming the video file to just "a.mkv", and I have tried converting the video into plain h.264 (no audio, no subtitles, no other streams). I've tried short videos (0.5 seconds) and longer ones (about a minute long). All these instances cause the error.

If I select "Use Single Model", the video converts without problem. If I select "Chain Two Models" on a PNG image, the image converts without problem. I suspect the filename generated for the new video file (i.e. "Model1+Model2+oldFilename.extension") may contain some impossible character(s).

The error message is as follows:

```
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
Illegal characters in path.
```

The debug data reads as follows:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Cupscale.UI.VideoUpscaleUI.CopyBack(String path)
   at Cupscale.UI.VideoUpscaleUI.<Run>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Cupscale.Main.MainForm.<upscaleBtn_Click>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Cupscale
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Magick.NET.Core
    Assembly Version: 5.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.22.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Cyotek.Windows.Forms.ImageBox
    Assembly Version: 1.2.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
HTAlt WinForms
    Assembly Version: 0.1.6.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
HTAlt.Standart
    Assembly Version: 0.1.6.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
NvAPIWrapper
    Assembly Version: 0.8.0.98
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.0.1
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Cyotek.Windows.Forms.TabList
    Assembly Version: 2.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
PaintDotNet.Base
    Assembly Version: 3.36.7079.22820
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------
DdsFileTypePlus
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Becky/Apps/Cupscale/Cupscale.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Thank you so much for your time, and for making such a helpful frontend app.

**Comment by n00mkrad** [comment]
Yep, fixed that yesterday. Forgot to strip some characters out of the model suffix.

An update is coming soon that includes this fix.
