### ISSUE TITLE
Failed to convert Pytorch model to NCNN format! It might be incompatible.

### ISSUE THREAD

**Issue by rgm89git** [n00mkrad/cupscale#73]
I'm trying to upscale using 4x_CelFrames_1.0_G.pth, but this happened when converting the model to a NCNN model.

```
Failed to convert Pytorch model to NCNN format! It might be incompatible.

OSError: [WinError 182] O sistema operacional não pode executar %1

Stack Trace:
   em Cupscale.OS.NcnnUtils.<ConvertNcnnModel>d__6.MoveNext()
```

Please help me.

**Comment by n00mkrad** [comment]
Can you send your full log?

**Comment by rgm89git** [comment]
```

Running in portable mode. Data folder: C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData
Arg: C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\Cupscale.exe
Detected Card: NVIDIA GeForce MX110 / GPU: GM108-B / Arch: Maxwell
Initialized Nvidia API. GPU: NVIDIA GeForce MX110
[DepCheck] CMD: /C python -V
[Servers] Ping to nmkd-hz.de: 239 ms
[Servers] Ping to nmkd-cb.de: 238 ms
[DepCheck] System Python Check Output: Python 3.9.2
[DepCheck] Sys Python Ver: Python 3.9.2
Parsing Patrons from CSV...
Found 15 Gold Patrons, 291 Silver Patrons
[Servers] Closest Server: USA (St. Louis) (238 ms)
[DepCheck] Refreshing...
[DepCheck] Found GPU: Intel(R) UHD Graphics 620
[DepCheck] Skipping refresh - Only 713ms have passed since last refresh!
[DepCheck] First GPU Name: MX110
[DepCheck] CMD: /C python -V
[DepCheck] System Python Check Output: Python 3.9.2
[DepCheck] Sys Python Ver: Python 3.9.2
[DepCheck] CMD: /C "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\py\python.exe" -V
[DepCheck] Embed Python Check Output: 'C:\Users\RGM\Documents\Cupscale\Cupscale' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.
[DepCheck] Embed Python Ver: 'C:\Users\RGM\Documents\Cupscale\Cupscale' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.
[DepCheck] CMD: "/C" python -c "import torch; print(torch.__version__)"
[DepCheck] Pytorch Check Output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
[DepCheck] CMD: "/C" python -c "import cv2; print(cv2.__version__)"
[DepCheck] CV2 Check Output: 4.5.2
Downloading embedded Python from 'https://dl.nmkd-cb.de/flowframes/setupfiles/py-tu/v1/py-tu.7z'
[IOUtils] Copying directory "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\esrgan-pytorch\utils" to "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\py\utils" (Move: False - RemoveFromName: )
[DepCheck] Refreshing...
[DepCheck] Found GPU: Intel(R) UHD Graphics 620
[DepCheck] First GPU Name: MX110
[DepCheck] CMD: /C python -V
[DepCheck] System Python Check Output: Python 3.9.2
[DepCheck] Sys Python Ver: Python 3.9.2
[DepCheck] CMD: /C "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\py\python.exe" -V
[DepCheck] Embed Python Check Output: Python 3.8.5
[DepCheck] Embed Python Ver: Python 3.8.5
[DepCheck] CMD: "/C" "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\py\python.exe" -c "import torch; print(torch.__version__)"
[DepCheck] Pytorch Check Output: 1.6.0
[DepCheck] CMD: "/C" "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\py\python.exe" -c "import cv2; print(cv2.__version__)"
[DepCheck] CV2 Check Output: 4.3.0
Running ffmpeg...
cmd.exe /C cd /D "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin" & ffmpeg.exe -hide_banner -loglevel warning -y -stats -i "C:\Users\RGM\Downloads\Adventures of Super Mario Bros 3 - Intro.mp4" -compression_level 3  -vsync 0  "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\img-in/%04d.png"
[FFmpeg] frame=   70 fps=0.0 q=-0.0 size=N/A time=00:00:02.58 bitrate=N/A speed=5.14x    
[FFmpeg] frame=  141 fps=140 q=-0.0 size=N/A time=00:00:05.54 bitrate=N/A speed=5.49x    
[FFmpeg] frame=  231 fps=142 q=-0.0 size=N/A time=00:00:09.30 bitrate=N/A speed=5.71x    
[FFmpeg] frame=  356 fps=167 q=-0.0 size=N/A time=00:00:14.51 bitrate=N/A speed=6.82x    
[FFmpeg] frame=  471 fps=179 q=-0.0 size=N/A time=00:00:19.31 bitrate=N/A speed=7.33x    
[FFmpeg] frame=  565 fps=180 q=-0.0 size=N/A time=00:00:23.23 bitrate=N/A speed=7.41x    
[FFmpeg] frame=  672 fps=185 q=-0.0 size=N/A time=00:00:27.69 bitrate=N/A speed=7.62x    
[FFmpeg] frame=  754 fps=183 q=-0.0 Lsize=N/A time=00:00:31.48 bitrate=N/A speed=7.62x    
Done running ffmpeg.
Disk space check for C: with multiplier 2 - 254 MB needed, 94612 MB available
currentInDir: C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\img-in, imgInPath: C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\img-in
[Queue] Start()
ConvertNcnnModel: C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\models\4x_CelFrames_1.0_G.pth
Checking for NCNN model: C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\models\.ncnn-models\4x_CelFrames_1.0_G
Running model converter...
[CMD] /C cd /D "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\pth2ncnn" & pth2ncnn.exe "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\models\4x_CelFrames_1.0_G.pth"
[NcnnUtils] Model Converter Output: Traceback (most recent call last):
[NcnnUtils] Model Converter Output:   File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
[NcnnUtils] Model Converter Output:   File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
[NcnnUtils] Model Converter Output:   File "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\pth2ncnn\pth2ncnn.exe\__main__.py", line 5, in <module>
[NcnnUtils] Model Converter Output:   File "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\pth2ncnn\tools\lib\site-packages\torch\__init__.py", line 81, in <module>
[NcnnUtils] Model Converter Output:     ctypes.CDLL(dll)
[NcnnUtils] Model Converter Output:   File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 364, in __init__
[NcnnUtils] Model Converter Output: OSError: [WinError 182] O sistema operacional não pode executar %1
Failed to convert Pytorch model to NCNN format! It might be incompatible.

OSError: [WinError 182] O sistema operacional não pode executar %1

Stack Trace:
   em Cupscale.OS.NcnnUtils.<ConvertNcnnModel>d__6.MoveNext()
[ESRGAN] NCNN Model is ready: 
Failed to get NCNN model scale for dir '': Valor não pode ser nulo.
Nome do parâmetro: path
Failed to parse "Automatic (Recommended)" to int: A cadeia de caracteres de entrada não estava em um formato correto.
[CMD] /C cd /D "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\esrgan-ncnn" & esrgan-ncnn-vulkan.exe -i "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\img-in" -o "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\img-out" -g 0 -m "" -s 4  
[NCNN] [0 NVIDIA GeForce MX110]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[NCNN] [0 NVIDIA GeForce MX110]  buglssc=0  bugsbn1=0  buglbia=0  bugihfa=0
[NCNN] [0 NVIDIA GeForce MX110]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
[NCNN] [1 Intel(R) UHD Graphics 620]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[NCNN] [1 Intel(R) UHD Graphics 620]  buglssc=0  bugsbn1=0  buglbia=0  bugihfa=0
[NCNN] [1 Intel(R) UHD Graphics 620]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
[NCNN] _wfopen /x4.param failed
[Queue] Stop()
```

**Comment by rgm89git** [comment]
@n00mkrad maybe the problem is with the D:\ root.

i don't have an D:\ drive, so that maybe cause the problem.

**Comment by rgm89git** [comment]
@n00mkrad Ok, so.
Probably, the problem is on the pth2ncnn executable.
`string args = $"{opt} cd /D {ConverterDir.Wrap()} & pth2ncnn.exe {modelPath}";`
Output:
`[CMD] /C cd /D "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\bin\pth2ncnn" & pth2ncnn.exe "C:\Users\RGM\Documents\Cupscale\Cupscale 1.39.0f1\CupscaleData\models\4x_CelFrames_1.0_G.pth"`

**Comment by ImportTaste** [comment]
I'm having the same problem.
